version: '3.0'
services:
  consul:
    image: consul
    hostname: "registry"
    ports:
    - "8300:8300"
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"

  api:
#    command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10 api
    image: micro-service/api
    links:
    - consul
    ports:
    - "8080:8080"
  api-service:
     image: micro-service/api-service
     links:
     - consul
     - api
  order-service:
     image: micro-service/order-service
     links:
     - consul
     - api
  say-service:
     image: micro-service/say-service
     links:
     - consul
     - api
